services:
  - type: web
    name: agenda-sandvik-taubate
    env: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
