services:
  - type: web
    name: agenda-sandvik-taubate
    env: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    disk:
      name: agenda-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
